HOST: https://api.poniverse.net/v1/

--- Sample API v2 ---
---
Welcome to the our sample API documentation. All comments can be written in (support [Markdown](http://daringfireball.net/projects/markdown/syntax) syntax)
---

--
User Resources
--

Gets the "logged in user" (read: the user the access token is bound to)
GET /users{?access_token,string}
< 200
< Content-Type: application/json
{"id":3757,"username":"Lavoaster","display_name":"Lavoaster","slug":"","email":"adam@lavoaster.co.uk","last_login":"2013-10-24 19:21:03","created_at":"2012-04-21 14:25:07"}