FORMAT: 1A
HOST: https://api.poniverse.net


# Poniverse API

# Group Users

### GET /user/me
Returns information about the user the oauth access token belongs to.

+ Parameters
  + access_token (string, required) - OAuth Access Token.

+ Response 200 (application/json)

        {
            "id":3757,
            "username":"Lavoaster",
            "display_name":"Lavoaster",
            "email":"adam@lavoaster.co.uk"
        }